apiVersion: v1
kind: Service
metadata:
  name: my-devops-app
spec:
  type: LoadBalancer  # Changez NodePort en LoadBalancer
  ports:
    - port: 80        # Port externe du service
      targetPort: 5000  # Port interne de l'application Flask
  selector:
    app: my-devops-app
